[project]
name = "nim-quick-start"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tony Vu", email = "tony@apartmenttherapy.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.7",
    "openai>=3.14.1",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
nim-quick-start = "nim_quick_start:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
